name = "sce-api"
main = "src/index.ts"
compatibility_date = "2024-01-11"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "sce-api.pasttime.xyz", zone_name = "pasttime.xyz" }
]

[vars]
ENVIRONMENT = "production"

# To run locally, create a .dev.vars file with:
# DATABASE_ID=your-database-id-here
[[d1_databases]]
binding = "DB"
database_name = "sce-db"
database_id = "eca50171-09fe-48a7-be44-b20d85c6ed6c"
